# Generated by Django 3.2.9 on 2021-12-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_category_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
